CREATE TABLE check_in (
  id INTEGER PRIMARY KEY IDENTITY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  attendee_id VARCHAR(255) NOT NULL,
  CONSTRAINT fk_attendee_id FOREIGN KEY (attendee_id)
  REFERENCES attendee(id) ON DELETE RESTRICT ON UPDATE CASCADE
);